from io import TextIOWrapper
from typing import overload
from .. import GSUB_GPOSType, CFF_Type
from typing_extensions import Literal

class TTFont():
    def importXML(self, fileOrPath: str | TextIOWrapper) -> None: ...
    def saveXML(self, path: str) -> None: ...
    def save(self, path: str) -> None: ...
    @overload
    def __getitem__(self, key: Literal["GSUB"]) -> GSUB_GPOSType: ...
    @overload
    def __getitem__(self, key: Literal["GPOS"]) -> GSUB_GPOSType: ...
    @overload
    def __getitem__(self, key: Literal["CFF "]) -> CFF_Type: ...
